plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'androidx.navigation.safeargs'
    id 'com.google.devtools.ksp'
}

android {
    namespace 'com.bruce32.psnprofileviewer'
    compileSdk 35

    defaultConfig {
        applicationId "com.bruce32.psnprofileviewer"
        minSdk 33
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21
        freeCompilerArgs += [
            "-opt-in=kotlin.RequiresOptIn"
        ]
    }
    buildFeatures {
        viewBinding true
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {

    def coroutines = '1.7.3'
    def navigation = '2.8.8'
    def room = '2.6.1'
    def fragment = '1.8.6'
    def glide = '4.13.2'
    def retrofit = '2.9.0'

    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines"
    implementation 'org.jsoup:jsoup:1.15.2'
    implementation "com.squareup.retrofit2:retrofit:$retrofit"
    implementation "com.squareup.retrofit2:converter-scalars:$retrofit"
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.5.1'
    implementation "androidx.fragment:fragment-ktx:$fragment"
    implementation "com.github.bumptech.glide:glide:$glide"
    implementation "androidx.navigation:navigation-fragment-ktx:$navigation"
    implementation "androidx.navigation:navigation-ui-ktx:$navigation"
    implementation "androidx.room:room-runtime:$room"
    implementation "androidx.room:room-ktx:$room"

    ksp "androidx.room:room-compiler:$room"
    ksp "com.github.bumptech.glide:compiler:$glide"

    debugImplementation "androidx.fragment:fragment-testing:$fragment"

    def espresso = '3.6.1'
    def junit_androidx = '1.2.1'

    testImplementation 'junit:junit:4.13.2'
    testImplementation "io.mockk:mockk:1.13.10"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutines"
    testImplementation "org.robolectric:robolectric:4.14.1"
    testImplementation "androidx.test.ext:junit:$junit_androidx"
    testImplementation "androidx.test.espresso:espresso-core:$espresso"
    testImplementation "org.apache.commons:commons-text:1.6"

    androidTestImplementation "androidx.test.ext:junit:$junit_androidx"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espresso"
}